package game

import (
	"bufio"
	"fmt"
	"os"
	"projet-red_POLARIS/internal/character"
	"projet-red_POLARIS/internal/menu"
	"projet-red_POLARIS/utils"
	"time"
)

// InitGame initializes the game by creating a character and starting the main
// game loop, which allows the player to access the menu.
func InitGame() {
	utils.Clearscreen()
	fmt.Println("\n")
	fmt.Println("░▒▓███████▓▒░")
	fmt.Println("░▒▓█▓▒░░▒▓█▓▒░")
	fmt.Println("░▒▓█▓▒░░▒▓█▓▒░")
	fmt.Println("░▒▓███████▓▒░")
	fmt.Println("░▒▓█▓▒░      ")
	fmt.Println("░▒▓█▓▒░      ")
	fmt.Println("░▒▓█▓▒░       ")
	fmt.Println("\n\n\n")
	time.Sleep(150 * time.Millisecond)
	utils.Clearscreen()
	fmt.Println("\n")
	fmt.Println("░▒▓███████▓▒░ ░▒▓██████▓▒░")
	fmt.Println("░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░")
	fmt.Println("░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░")
	fmt.Println("░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░")
	fmt.Println("░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░")
	fmt.Println("░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░")
	fmt.Println("░▒▓█▓▒░       ░▒▓██████▓▒░")
	fmt.Println("\n\n\n")
	time.Sleep(150 * time.Millisecond)
	utils.Clearscreen()
	fmt.Println("\n")
	fmt.Println("░▒▓███████▓▒░ ░▒▓██████▓▒░░▒▓█▓▒░")
	fmt.Println("░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░")
	fmt.Println("░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░")
	fmt.Println("░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░")
	fmt.Println("░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░")
	fmt.Println("░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░")
	fmt.Println("░▒▓█▓▒░       ░▒▓██████▓▒░░▒▓████████▓▒░")
	fmt.Println("\n\n\n")
	time.Sleep(150 * time.Millisecond)
	utils.Clearscreen()
	fmt.Println("\n")
	fmt.Println("░▒▓███████▓▒░ ░▒▓██████▓▒░░▒▓█▓▒░       ░▒▓██████▓▒░")
	fmt.Println("░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░")
	fmt.Println("░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░")
	fmt.Println("░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓████████▓▒░")
	fmt.Println("░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░")
	fmt.Println("░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░")
	fmt.Println("░▒▓█▓▒░       ░▒▓██████▓▒░░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░")
	fmt.Println("\n\n\n")
	time.Sleep(150 * time.Millisecond)
	utils.Clearscreen()
	fmt.Println("\n")
	fmt.Println("░▒▓███████▓▒░ ░▒▓██████▓▒░░▒▓█▓▒░       ░▒▓██████▓▒░░▒▓███████▓▒░")
	fmt.Println("░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░")
	fmt.Println("░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░")
	fmt.Println("░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓████████▓▒░▒▓███████▓▒░")
	fmt.Println("░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░")
	fmt.Println("░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░")
	fmt.Println("░▒▓█▓▒░       ░▒▓██████▓▒░░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░")
	fmt.Println("\n\n\n")
	time.Sleep(150 * time.Millisecond)
	utils.Clearscreen()
	fmt.Println("\n")
	fmt.Println("░▒▓███████▓▒░ ░▒▓██████▓▒░░▒▓█▓▒░       ░▒▓██████▓▒░░▒▓███████▓▒░░▒▓█▓▒░")
	fmt.Println("░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░")
	fmt.Println("░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░")
	fmt.Println("░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓████████▓▒░▒▓███████▓▒░░▒▓█▓▒░")
	fmt.Println("░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░")
	fmt.Println("░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░")
	fmt.Println("░▒▓█▓▒░       ░▒▓██████▓▒░░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░")
	fmt.Println("\n\n\n")
	time.Sleep(150 * time.Millisecond)
	utils.Clearscreen()
	fmt.Println("\n")
	fmt.Println("░▒▓███████▓▒░ ░▒▓██████▓▒░░▒▓█▓▒░       ░▒▓██████▓▒░░▒▓███████▓▒░░▒▓█▓▒░░▒▓███████▓▒░ ")
	fmt.Println("░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░▒▓█▓▒░        ")
	fmt.Println("░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░▒▓█▓▒░        ")
	fmt.Println("░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓████████▓▒░▒▓███████▓▒░░▒▓█▓▒░░▒▓██████▓▒░  ")
	fmt.Println("░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░ ")
	fmt.Println("░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░ ")
	fmt.Println("░▒▓█▓▒░       ░▒▓██████▓▒░░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░▒▓███████▓▒░  ")
	fmt.Println("\n\n")
	time.Sleep(150 * time.Millisecond)
	fmt.Println("Press Enter to START !")

	_, _ = bufio.NewReader(os.Stdin).ReadString('\n')

	c1 := character.InitCharacter()
	
	utils.Clearscreen()
	fmt.Println("Welcome to Polaris !")
	time.Sleep(2 * time.Second)
	menu.ShowMenu(&c1)
}
